# Generated by Django 4.2.4 on 2023-09-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
